### ISSUE TITLE
No display of questions

### ISSUE THREAD

**Issue by crschmidt** [Hennamann/Live-Chat-Question-Flagger#12]
As of 8c1e44007b06de5895e733ce2436885751e7159d, attempting to click the "?" in the UI causes no questions to appear on the right hand side. The UI doesn't appear to match what is displayed in the screenshots at all: It appears that the split screen with the "Questions" view in modview.html is not actually what is checked in?

Any chance you may have a slightly out of date UI checked in for modview.html, or something obvious I'm missing in the setup? the source HTML doesn't appear to have any handling for displaying questions selected...

**Comment by crschmidt** [comment]
Okay, I see now:

 the "/" view is the "modview", where moderators can select questions
 the "/hostview" is the view for the host, to pick the questions and actually generate lower thirds

Is that right?

As someone who is my own mod + host, having these in two separate views (which appears recent) isn't super helpful to me; there isn't a combined view anymore, right?

(Related question: is there a way to *remove* a lowerthird once you've generated one? e.g. "I've answered this question and have no others that it's time for...")

**Comment by Hennamann** [comment]
As mentioned in the Readme, the documentation and instructions are slightly outdated, but you figured it out on your own. I agree the new system is not optimal for self-hosters, which is why the plan is to eventually change it to what has been suggested here: #10.
Feel free to add suggestions on other ways to improve it over on that issue.

As for removing a lower third, the general idea is that you hide your overlay in OBS(or whatever you are using) when you have read all the questions, another solution is to refresh the lower-third view in the browser. I might add a button somewhere that removes the current lower third, any suggestions for where you'd want to see this button?

**Comment by imikerussell** [comment]
@crschmidt as @Hennamann mentions you can hide the overlay in OBS Studio by clicking the eye icon.

![screen shot 2017-09-06 at 16 03 31](https://user-images.githubusercontent.com/5058188/30119272-1cd46204-931d-11e7-98d8-e726779ba346.png)

When it has a line through the eye icon your lower third will be hidden until you need it again.

![screen shot 2017-09-06 at 16 03 40](https://user-images.githubusercontent.com/5058188/30119271-1cd066e0-931d-11e7-8709-bed9ade2a1ca.png)
